apiVersion: apps/v1
kind: Deployment
metadata:
  name: gregfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gregfs
  template:
    metadata:
      labels:
        app: gregfs
    spec:
      containers:
      - image: okteto.dev/gregfs:latest
        name: gregfs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ee3c2e12-b784-4d4d-ba4f-d917ce9faef4"
        - name: Vless_Path
          value: "/ee3c2e12-b784-4d4d-ba4f-d917ce9faef4-vless"
        - name: Vmess_UUID
          value: "ee3c2e12-b784-4d4d-ba4f-d917ce9faef4"
        - name: Vmess_Path
          value: "/92caf4c9-5089-4e7b-ab07-073773aa1fde-vmess"
        - name: Share_Path
          value: "$Share_Path"
